# Generated by Django 5.2.11 on 2026-02-16 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Correo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correo_id', models.IntegerField(unique=True)),
                ('asunto', models.CharField(blank=True, max_length=255)),
                ('cuerpo', models.TextField(blank=True)),
                ('categoria', models.CharField(choices=[('pqr', 'PQR'), ('demanda', 'Demanda'), ('tutela', 'Tutela'), ('ninguno', 'Ninguno')], max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
